// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"database/sql"
	"time"
)

type Animetime struct {
	Guid      string
	Title     string
	Link      string
	Category  string
	Pubdate   string
	Infohash  sql.NullString
	CreatedAt time.Time
	Size      int64
	Seeders   sql.NullInt64
	Peers     sql.NullInt64
}
